### ISSUE TITLE
Responder does to open the needed ports 443,445,5533,53 and other ports and says check premissions

### ISSUE THREAD

**Issue by sergiobakaning** [SpiderLabs/Responder#111]
Hey Guys,

My responder is not working it wants to setup servers on different ports but can't and ask if any other service is running on the port answer is no. i did responder -I eth0 -i 192.168.0.1 and i get 

[!] Error starting UDP server on port 5355, check permissions or other servers running.
[!] Error starting UDP server on port 5353, check permissions or other servers running.
[!] Error starting TCP server on port 80, check permissions or other servers running.
[!] Error starting SSL server on port 443, check permissions or other servers running.
[!] Error starting UDP server on port 88, check permissions or other servers running.
 [!] Error starting TCP server on port 139, check permissions or other servers running.[!] Error starting TCP server on port 445, check permissions or other servers running.[!] Error starting TCP server on port 88, check permissions or other servers running.

[!] Error starting TCP server on port 1433, check permissions or other servers running.
[!] Error starting TCP server on port 21, check permissions or other servers running.
[!] Error starting TCP server on port 110, check permissions or other servers running.
[!] Error starting TCP server on port 389, check permissions or other servers running.
 [!] Error starting TCP server on port 25, check permissions or other servers running.
[!] Error starting TCP server on port 587, check permissions or other servers running.
[!] Error starting TCP server on port 143, check permissions or other servers running.
 [!] Error starting UDP server on port 53, check permissions or other servers running.
[+] Listening for events...
[!] Error starting TCP server on port 53, check permissions or other servers running.

permissions are the same i installed mitmf is that the issue ?

please help me ....

Sergio

**Comment by sergiobakaning** [comment]
fixed it. it was a noob problem

**Comment by musyoka101** [comment]
i have the same problem how do i fix it please

**Comment by Ap6pack** [comment]
This was the error is was having: [!] Error starting TCP server on port 80, check permissions or other servers running. The way i fixed it was by killing my Apache server while using Responder.
