### ISSUE TITLE
Get NTLM hashes [HELP WANTED]

### ISSUE THREAD

**Issue by reteps** [SpiderLabs/Responder#133]
Hello. I just started programming, and I don't know what all the options do. What options do I need to I  run this and retrieve just the NTLM hashes (on a mac)? And where will this output the hashes? Thanks in advance.

**Comment by dinvisible1** [comment]
congrats on starting programming!

as for you question of not knowing what to do i would recommend reading up on what the tool is used for, this as well as what the options are, can be found here https://github.com/SpiderLabs/Responder lower down on the page.

I would say read up on what the tool does and try to understand that before trying to fiddle around with it, once you know that you have a look at the possible option and what they do and with you're new found understanding things should be clearer.

as for the on a mac, maybe an understanding of how the OS works might be able to shed some light on that, I dont use a mac per say but i am sure google can assist you in assisting you're self. keep in mind that this tool run on linux.

keeping this short i would like to add that, you "question" is not so much and "issue" but more of a request for information that I am pretty sure you can find on your own. If you find that I am rude in my response, i do apologize, but try to understand that what you are asking for and where you are asking for it was not designed for "those" type of question.

thank you and good day.

**Comment by reteps** [comment]
thanks for the detailed response.

**Comment by videoman** [comment]
This code base is no longer maintained. https://github.com/lgandx/Responder
