### ISSUE TITLE
no Hash possible when the Username has a space in the name

### ISSUE THREAD

**Issue by pixelwasser** [SpiderLabs/Responder#138]
Hello,
I have found maybe an issue. Currently it seems that responder is only able to collect hashes from single user Name like "DemoUser" if there is a space in the Username like "Demo User" the script tries to collect the hash from "Demo" which doesn't exist on the machine.

As a target I used a Windows 10 1607.

Sincerley
Jan

**Comment by videoman** [comment]
This repo is no longer maintained. Please use https://github.com/lgandx/Responder

**Comment by pixelwasser** [comment]
Thank you
