### ISSUE TITLE
 Error starting TCP server on port 443

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/Responder#36]
hey i get this error on most networks " Error starting TCP server on port 443. Check that you have the necessary permissions (i.e. root), no other servers are running and the correct network interface is set in Responder.conf. " and sometimes its a different port. can someone help?

**Comment by limited-root** [comment]
my netstat output is:
tcp6       0      0 :::443                  :::*                    LISTEN 
how could i kill it to make responder work for ssl?

**Comment by hktalent** [comment]
#124 #36  #45
