### ISSUE TITLE
Question regarding use

### ISSUE THREAD

**Issue by DrDinosaur** [SpiderLabs/Responder#37]
Hi, this is more of a question rather than a bug. How do you use this program on the LAN of a compromised machine? Say you have your Kali box somewhere on the Internet and you compromise a workstation in the internal network with a client side attack. You have access to that machine now, say with Meterpreter. How do you use this tool on the compromised target's LAN? I believe this is a common scenario and probably has a simply answer, but all the demos of this tool I read seemed to have the Kali box already on the LAN. Thanks.

**Comment by ravenium** [comment]
(disclaimer - all hypotheticals based on legitimate authorized penetration testing or other approved activities)

It would depend on the platform of the compromised machine. For example, if you were to compromise a Mac, you have a good chance of Python being pre-installed on the system. Thus, you'd be able to run Responder without much effort.  For Windows systems, the presence of Python is significantly less common (unless specifically installed), so you have the option of 1. installing python (rather intrusive) or trying to run it through py2exe (haven't tried this myself).

**Comment by DrDinosaur** [comment]
So you need to install Python (does this need admin privileges?) on a host
in the network? Can you do any networking techniques to still have it work
on you attack machine? You mentioned installing Python on the host is
intrusive and you haven't tried py2exe. Is this not the typical use case?
If not, how is the tool typically used in penetration testing? Would the
tool still work on a Windows host that's already listening on the ports
responder uses (typical, no?)? Thanks.

**Comment by ravenium** [comment]
The typical use case for responder is, in my opinion, as part of a toolset for a "rogue" host (that you have root on) that is dropped onto an internal network (one of the common scenarios for black box internal pen testing). Part of my reasoning is that you need to open numerous low-range ports (137/139/443/445/etc), which are often running other services on a typical host (not to mention that these are privileged ports, etc). This goes doubly so for Windows, where disabling file sharing is more involved. Disabling these services either is very conspicuous (something not desired if your engagement requires some degree of stealth), or disruptive at best.

If you're looking for the scenario of external compromise to internal network, I'd recommend spending some time exploring the art of using the tools already on a compromised system via built in language/scripting features.  You could write a connect back in Windows Powershell, for example, vs dropping a potentially risky binary.

Anyhow, not to say that Responder can't be used in the type of scenario you described, but it's definitely not the optimal platform or use case.

**Comment by DrDinosaur** [comment]
Ah okay, thanks for the clarification.
