### ISSUE TITLE
Enhancement request: SMB file serving support

### ISSUE THREAD

**Issue by Viss** [SpiderLabs/Responder#38]
So you're on a social engineering engagement, right?
And you want to do that trick where you link an image in an email via a UNC path so that outlook lobs a hash your way - except the image you include turns out to not exist and they get a broken link image in the email, and they get suspicious. 

How about allowing responder to be pointed to a directory where you can put the image(s) or other files so things don't look broken? That would be kind of neat :D

**Comment by videoman** [comment]
Could you make the image 1px x 1px? 

You would also then have to either be running Responder inside their network - or on the Internet.  Adding a complete SMB stack for file sharing to Responder seems kind of like overkill if all you want to do is grab hashes/challenges from the clients.

**Comment by lanjelot** [comment]
in the meantime you could just use impacket/smbserver.py which will host your images and capture the hashes

**Comment by Viss** [comment]
@videoman: the trouble with that is the broken image will still appear in some cases. I'm not necessarily asking for a whole smb stack, per se, just the ability to serve one image file so that links don't appear broken. 

@lanjelot: I shall look into it!
