### ISSUE TITLE
Error starting TCP server on port 443.

### ISSUE THREAD

**Issue by leebaird** [SpiderLabs/Responder#41]
root@kali:~# responder -i 172.18.233.45 -I eth0 -wrf
NBT Name Service/LLMNR Responder 2.0.
Please send bugs/comments to: lgaffie@trustwave.com
To kill this script hit CRTL-C

[+]NBT-NS, LLMNR & MDNS responder started
[+]Loading Responder.conf File..
Global Parameters set:
Responder is bound to this interface: eth0
Challenge set: 1122334455667788
WPAD Proxy Server: True
WPAD script loaded:  function FindProxyForURL(url, host){if ((host == "localhost") || shExpMatch(host, "localhost.*") ||(host == "127.0.0.1") || isPlainHostName(host)) return "DIRECT"; if (dnsDomainIs(host, "RespProxySrv")||shExpMatch(host, "(*.RespProxySrv|RespProxySrv)")) return "DIRECT"; return 'PROXY ISAProxySrv:3141; DIRECT';}
HTTP Server: ON
HTTPS Server: ON
SMB Server: ON
SMB LM support: False
Kerberos Server: ON
SQL Server: ON
FTP Server: ON
IMAP Server: ON
POP3 Server: ON
SMTP Server: ON
DNS Server: ON
LDAP Server: ON
FingerPrint hosts: True
Serving Executable via HTTP&WPAD: OFF
Always Serving a Specific File via HTTP&WPAD: OFF

Error starting TCP server on port 443. Check that you have the necessary permissions (i.e. root), no other servers are running and the correct network interface is set in Responder.conf.
^Croot@kali:~# 

root@kali:~# netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5984          0.0.0.0:*               LISTEN      24441/beam.smp

**Comment by lgandx** [comment]
If nothing is listening on 443, it must be an implementation issue. Please check with Kali Team.

**Comment by leebaird** [comment]
Opened a ticket with the Kali team.

**Comment by Zaxscdvf** [comment]
have the same problem.

**Comment by ZephrFish** [comment]
did you  discover the fault?

**Comment by leebaird** [comment]
Muts discovered and corrected the issue. There was a file that was not included in the package.

**Comment by ZephrFish** [comment]
has it been fixed in an update then?
