### ISSUE TITLE
can't listen on some ports (5353,5355)

### ISSUE THREAD

**Issue by royharoush** [SpiderLabs/Responder#45]
Hi,
on 2 different kali machines, running as root, i get the following error. 
----------------------------------
Error starting UDP server on port 5353. Check that you have the necessary permissions (i.e. root), no other servers are running and the correct network interface is set in Responder.conf.
 Error starting UDP server on port 5355. Check that you have the necessary permissions (i.e. root), no other servers are running and the correct network interface is set in Responder.conf.
Croot@kali-vm:~/Responder# 
---------------------------------

i've tried using the built in version and cloning from git. 
nothing is actually listening on these ports 

----
root@kali-vm:~/Responder# netstat -a | egrep 'Proto|LISTEN' 
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp6       0      0 [::]:http               [::]:*                  LISTEN     
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     837      /tmp/.ICE-unix/3925
unix  2      [ ACC ]     STREAM     LISTENING     17152    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     18866    /tmp/pulse-tbWWOQ4ywjyT/native
unix  2      [ ACC ]     STREAM     LISTENING     18868    /tmp/pulse-tbWWOQ4ywjyT/dbus-socket
unix  2      [ ACC ]     STREAM     LISTENING     836      @/tmp/.ICE-unix/3925
unix  2      [ ACC ]     STREAM     LISTENING     20560    @/tmp/dbus-YVTEc5ZfjE
unix  2      [ ACC ]     STREAM     LISTENING     14297    @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     14298    /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     18622    @/tmp/gdm-session-ryoyfIWr
unix  2      [ ACC ]     STREAM     LISTENING     1794     /tmp/ssh-LPmWpZuQdB9t/agent.3925
unix  2      [ ACC ]     STREAM     LISTENING     18810    /root/.cache/keyring-rHRhJk/gpg
unix  2      [ ACC ]     STREAM     LISTENING     15236    @/tmp/dbus-gxyqmSDBCW
unix  2      [ ACC ]     STREAM     LISTENING     14266    /var/run/pcscd/pcscd.comm
unix  2      [ ACC ]     STREAM     LISTENING     15198    /root/.cache/keyring-rHRhJk/control
unix  2      [ ACC ]     STREAM     LISTENING     18811    /root/.cache/keyring-rHRhJk/ssh
unix  2      [ ACC ]     STREAM     LISTENING     18812    /root/.cache/keyring-rHRhJk/pkcs11
unix  2      [ ACC ]     SEQPACKET  LISTENING     11492    /run/udev/control

----

any idea what could be causing this ? 
Thanks,
Roy

**Comment by hktalent** [comment]
#124 #36  #45
