### ISSUE TITLE
Ctrl-C not killing

### ISSUE THREAD

**Issue by DanMcInerney** [SpiderLabs/Responder#51]
On fully updated Kali 1.0 Ctrl-C no longer appears to kill it. It brings up the "Exiting..." message then just keeps on trucking indefinitely.

**Comment by lgandx** [comment]
I'm not sure about Kali as I don't have that version, but sometimes when the WPAD proxy is enabled CRTL-C doesn't kill Responder.  This is a known issue in the WPAD server, a temporary fix would be to run : ps faux|grep "Responder.py" and kill that process.
