### ISSUE TITLE
MSSQL.py Servers Code Error

### ISSUE THREAD

**Issue by emwinkler** [SpiderLabs/Responder#52]
Code error identified in MSSQL.py

 NtHash        = SSPIStart[NthashOffset:NthashOffset+NthashLen].encode("hex").upper()

should be

 NTHash        = SSPIStart[NthashOffset:NthashOffset+NthashLen].encode("hex").upper()

otherwise WriteHash function will fail.

**Comment by lgandx** [comment]
Fixed! Nice catch.
