### ISSUE TITLE
When will OSX be supported again?

### ISSUE THREAD

**Issue by infolookup** [SpiderLabs/Responder#53]
Same issue as issue #50  unable to run responder from my OS X 10.10.5 machine.

**Comment by lgandx** [comment]
I'm not exactly sure when i'll have the time to fix this, so please use V2.1.4 (which supports osx) in the meantime: https://github.com/SpiderLabs/Responder/releases

**Comment by lgandx** [comment]
Problem solved, please use the latest release.
