### ISSUE TITLE
Import Errors running SMBRelay.py

### ISSUE THREAD

**Issue by THExREALxASR** [SpiderLabs/Responder#60]
Hello. I wanted to be running the latest version in Kali 2.0 so I installed via Git under my /opt directory. When trying to run SMBRelay.py I seem to be getting a lot of import errors as such:

python SMBRelay.py 
Traceback (most recent call last):
  File "SMBRelay.py", line 17, in <module>
    import sys, os, struct,re,socket,random, RelayPackets,optparse,thread
  File "/opt/Responder/tools/RelayPackets.py", line 18, in <module>
    from odict import OrderedDict
ImportError: cannot import name OrderedDict

placing the odict.py script in the tools directory gives me this:
Traceback (most recent call last):
  File "SMBRelay.py", line 18, in <module>
    from fingerprint import RunSmbFinger
ImportError: No module named fingerprint

placing the fingerprint.py script in the tools directory gives me this:
python SMBRelay.py 
Traceback (most recent call last):
  File "SMBRelay.py", line 18, in <module>
    from fingerprint import RunSmbFinger
  File "/opt/Responder/tools/fingerprint.py", line 24, in <module>
    from utils import *
  File "/opt/Responder/tools/utils.py", line 23, in <module>
    import settings

and finally placing settings.py in tools directory gives me this:
python SMBRelay.py 
Traceback (most recent call last):
  File "SMBRelay.py", line 18, in <module>
    from fingerprint import RunSmbFinger
  File "/opt/Responder/tools/fingerprint.py", line 24, in <module>
    from utils import *
  File "/opt/Responder/tools/utils.py", line 23, in <module>
    import settings
  File "/opt/Responder/tools/settings.py", line 24, in <module>
    from utils import IsOsX
ImportError: cannot import name IsOsX

**Comment by THExREALxASR** [comment]
So it looks like utils is called twice in settings.py. Once I commented out this line:
#from utils import IsOsX
and copied packets.py into the tools directory, SMBRelay.py seemed to work or at least run without error.

**Comment by THExREALxASR** [comment]
Now I get the following:
Target is running:  ('Windows Server (R) 2008 Standard 6002 Service Pack 2', 'Windows Server (R) 2008 Standard 6.0')
Unhandled exception in thread started by <function RunInloop at 0x7f1c9a677230>
Traceback (most recent call last):
  File "SMBRelay.py", line 425, in RunInloop
    worker = RunRelay(Target,Command,Domain)
  File "SMBRelay.py", line 248, in RunRelay
    buffer0 = longueur(packet0)+packet0
NameError: global name 'longueur' is not defined

**Comment by Maleus** [comment]
Im having the same issues, exact same messages.

**Comment by jbagel2** [comment]
Me too.

**Comment by mw3demo** [comment]
Might be due to the python version in the 2.0 repo. 

Try installing via virtualenv.

I.e.

    pip install virtualenv
    source /usr/local/bin/virtualenvwrapper.sh
    mkvirtualenv Responder -p /usr/bin/python2.7
    git clone https://github.com/SpiderLabs/Responder.git
    cd Responder
    Python Responder.py

**Comment by lgandx** [comment]
The tools folder will be reviewed in depth and updated soon. 

Thanks for your report!

**Comment by Snizz** [comment]
Looking to see if any updates were available, seeing similar results as mw3demo mentioned.
```
Responder SMBRelay 0.1
Please send bugs/comments to: lgaffie@trustwave.com
Use this script in combination with Responder.py for best results (remember to set SMB = Off in Responder.conf)..
Usernames  to relay (-u) are case sensitive.
To kill this script hit CRTL-C or Enter
Will relay credentials for these users: XXXXX

Target is running:  ('Windows 7 Professional 7601 Service Pack 1', 'Windows 7 Professional 6.1')
Unhandled exception in thread started by <function RunInloop at 0x7ff2e594bb18>
Traceback (most recent call last):
  File "./SMBRelay.py", line 426, in RunInloop
    worker = RunRelay(Target,Command,Domain)
  File "./SMBRelay.py", line 249, in RunRelay
    buffer0 = longueur(packet0)+packet0
NameError: global name 'longueur' is not defined

```

**Comment by Snizz** [comment]
FWIW - Compared version 2.3 to 2.1.2. 

Version 2.1.2 works just fine.

**Comment by lgandx** [comment]
Should be working fine now..
Thanks for your report.
