### ISSUE TITLE
[Bug] HTTP-Basic-ClearText do not store the credentials on the txt file

### ISSUE THREAD

**Issue by fefafefa** [SpiderLabs/Responder#62]
Hello Responder developers! :)

The bug I have found it is that the Responder capture the users/passwords and show them on the console, but the generate files (HTTP-Basic-ClearText-*.txt) are empty.

Thanks for this wonderful pen-testing software! :D

Fefafefa

**Comment by lgandx** [comment]
Please provide an example.

**Comment by the-useless-one** [comment]
Hi all, my [pull request](https://github.com/SpiderLabs/Responder/pull/67) should address this problem.

Thanks!
