### ISSUE TITLE
SSLv3

### ISSUE THREAD

**Issue by mubix** [SpiderLabs/Responder#65]
Is there a way to disable SSLv3 in responder? I'm getting this:
```
Unable to Connect Securely

Firefox cannot guarantee the safety of your data because it uses SSLv3, a broken security protocol.
Advanced info: ssl_error_unsupported_version
```

Chrome/Firefox/IE same deal

**Comment by xenocons** [comment]
@mubix no idea if this will work, perhaps you can change https://github.com/SpiderLabs/Responder/blob/master/servers/HTTP.py#L276 to be SSL.TLSv1_METHOD, I have had issues on latest debian with responder as openssl gets compiled without SSLv3 support and breaks responder HTTPS.

**Comment by rhertzog** [comment]
@xenocons that's the correct analysis, SSL.SSLv23_METHOD also works as this flag basically tells OpenSSL "whatever you support", including TLS. Cf https://openssl.org/docs/manmaster/ssl/SSL_CTX_new.html Note that the unversioned "TLS_METHOD" does not appear to be available in the current python-openssl in Kali yet.

**Comment by rhertzog** [comment]
@lgandx Would you mind doing a release with the latest changes?

**Comment by rhertzog** [comment]
Why has this been closed if the fix did not yet land in master?
