### ISSUE TITLE
NTLMv1 hash captured not accurate

### ISSUE THREAD

**Issue by naterobbified** [SpiderLabs/Responder#66]
Used responder in my test lab to capture NTLMv1 hash, it wasn't working when I tried to use it to pass the hash with psexec  metaploit module. I logged in with psexec using the password, dumped the hash to compare, and the hash values are different. Would there be a reason responder wouldn't pull the correct hash values?

**Comment by videoman** [comment]
You can't "pass" a challenge hash.

**Comment by CheeseNuggets** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa378749%28v=vs.85%29.aspx

**Comment by picchioni** [comment]
You should try cracking your test password with hashcat or John, you'll see that it's indeed correct.
