### ISSUE TITLE
Error starting SSL server on port 443 on Kali Rolling distro

### ISSUE THREAD

**Issue by h121h** [SpiderLabs/Responder#70]
This is probably a rookie move and something simple I'm overlooking but I'm receiving this error on the new Kali Linux rolling distro.

"Error starting SSL server on port 443"

"netstat -lnpt" output shows nothing is listening on 443.

_#netstat -lnpt_
_#Active Internet connections (only servers)_
_#Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name_

**Comment by rhertzog** [comment]
This is a duplicate of #65. The reason why the SSL server doesn't start is that SSLv3 is disabled in Debian's OpenSSL.

**Comment by h121h** [comment]
Well, that makes sense. Thanks for the explanation @rhertzog.
