### ISSUE TITLE
Responder IP Showing Wrong IP Address

### ISSUE THREAD

**Issue by Catopuss** [SpiderLabs/Responder#71]
Hello, 

When I run Responder and provide my eth0 interface I see under Generic Options the "Responder IP" is showing the wrong IP address. It should be showing my 192.168 address that is currently setup on that interface but it's showing a different IP address that is related to the IP it receives when I'm in the office not the host only IP address. 

Would there be a reason it won't let go of a previous IP address and not giving my current IP address that is on eth0?

**Comment by lgandx** [comment]
You can use -I [INTERFACE] or -i and specify your own IP address.
