### ISSUE TITLE
OSX usage typos

### ISSUE THREAD

**Issue by Chewvala** [SpiderLabs/Responder#79]
I think in the readme file the following lines are wrong:
`launchcl unload /System/Library/LaunchDaemons/com.apple.Kerberos.kdc.plist

launchcl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist

launchcl unload /System/Library/LaunchDaemons/com.apple.smbd.plist

launchcl unload /System/Library/LaunchDaemons/com.apple.netbiosd.plist`

I think they need to read:
`launchctl unload /System/Library/LaunchDaemons/com.apple.Kerberos.kdc.plist

launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist

launchctl unload /System/Library/LaunchDaemons/com.apple.smbd.plist

launchctl unload /System/Library/LaunchDaemons/com.apple.netbiosd.plist`

**Comment by ravenium** [comment]
Added pull request
