### ISSUE TITLE
Basic authentication option isn't working

### ISSUE THREAD

**Issue by sdcampbell** [SpiderLabs/Responder#88]
I specified the -b and -F options for basic auth and it's not capturing credentials. The host is a Kali rolling virtual machine. The target is Windows 7 with IE11 joined to a lab domain. The target doesn't see a prompt for credentials from basic auth. The IE option to automatically detect settings is checked.

**Comment by sdcampbell** [comment]
I checked Responder v2.2 with IE11 and that version didn't work with basic authentication either. I tried both version 2.2 and 2.3 with IE10 and they work with basic authentication.

**Comment by lgandx** [comment]
I cannot reproduce, working fine on my end.
