### ISSUE TITLE
Undefined function IsOsX

### ISSUE THREAD

**Issue by ilmila** [SpiderLabs/Responder#89]
Unable to run Responder in Analyze mode.
Steps to reproduce the issue:
1. Git clone the project 
2. execute the command ` sudo python Responder.py -A -i eth0`. Result

```
sudo python Responder.py -A -i eth0
                                         __
  .----.-----.-----.-----.-----.-----.--|  |.-----.----.
  |   _|  -__|__ --|  _  |  _  |     |  _  ||  -__|   _|
  |__| |_____|_____|   __|_____|__|__|_____||_____|__|
                   |__|

           NBT-NS, LLMNR & MDNS Responder 2.3

  Author: Laurent Gaffie (laurent.gaffie@gmail.com)
  To kill this script hit CRTL-C

Traceback (most recent call last):
  File "Responder.py", line 55, in <module>
    settings.Config.populate(options)
  File "/tmp/Responder/settings.py", line 69, in populate
    if options.Interface is None and IsOsX() is False:
NameError: global name 'IsOsX' is not defined

```

The `IsOsX` function is defined twice in utils.py

Tested on:
 * OS Ubuntu 14.04.4
 * Python 2.7

**Comment by sdcampbell** [comment]
The "-i" option is only for OSX. For Linux, use "-I eth0" (Capital i), as stated in the command line help (Responder.py -h) as well as the project documentation:

For OSX, please note: Responder must be launched with an IP address for the -i flag (e.g. -i YOUR_IP_ADDR). There is no native support in OSX for custom interface binding. Using -i en1 will not work.

**Comment by ibhooyah** [comment]
I'm getting the same issue while on OSX

python Responder.py -i 192.22.121.8 -w -r -f -v

> Traceback (most recent call last):
  File "Responder.py", line 55, in <module>
    settings.Config.populate(options)
  File "/Users/testing/Responder/settings.py", line 69, in populate
    if options.Interface is None and IsOsX() is False:
NameError: global name 'IsOsX' is not defined

Tested on:

- Darwin Kernel Version 15.5.0

- Python 2.7.10

**Comment by grizzer** [comment]
settings.py, line 69:

change "IsOsX()" to "utils.IsOsX()"

Kali 2.0 with Python 2.7.12rc1

**Comment by digininja** [comment]
Can confirm this is an issue on the latest version and that the fix above does solve the problem

**Comment by ibhooyah** [comment]
settings.py, line 69:

change "IsOsX()" to "utils.IsOsX()"

Tested on:
 
- Darwin Kernel Version 15.5.0

- Python 2.7.10


This worked  as a fix. 
Thank you!
