### ISSUE TITLE
Tagging of new releases

### ISSUE THREAD

**Issue by offensive-security** [SpiderLabs/Responder#91]
Hi Guys, 

It looks like you haven't tagged a new release for a while (since Oct 8, 2015). The Kali dev team monitors tagged releases and updates packages according to these tag updates. Would it be possible to tag your releases more often, perhaps even with minor version numbers? This would help us to keep your tool fresh and constantly updated in Kali.

Thanks!

**Comment by lgandx** [comment]
Yes will do with the upcoming releases.
Thanks!

**Comment by lgandx** [comment]
I'm not supporting this repository anymore.
You can find updates and new releases here: https://github.com/lgandx/Responder
Thanks!
